name: socket
version: 0.0.2
author: Loi Nguyen <loint@penlook.com>
homepage: http://github.com/penlook/socket-client
description: Socket client for realtime based on long-polling
environment:
    sdk: '>=1.0.0 <2.0.0'
dependencies:
    shadow_dom: ">=0.10.0 <0.11.0"
dev_dependencies:
    browser: any
    unittest: any
